language: c

sudo: true

notifications:
  email: false

before_install:
  - wget https://github.com/devkitPro/pacman/releases/download/devkitpro-pacman-1.0.1/devkitpro-pacman.deb
  - sudo dpkg -i devkitpro-pacman.deb

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

cache:
    directories:
     - ~/.local/bin

install:
  - source ./.travis/prepare.sh

script:
  - cd $TRAVIS_BUILD_DIR
  - make clean && make
